export const SET_CRITERIA = 'SET_CRITERIA';
export const FETCH_ASSET = 'FETCH_ASSET';

export const FETCH_DATA_START = 'FETCH_DATA_START';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL';
