export const SET_CRITERIA = 'SET_CRITERIA';
export const FETCH_ASSET = 'FETCH_ASSET';

export const FETCH_DATA_START = 'FETCH_DATA_START';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL';

export const FETCH_ASSET_START = 'FETCH_ASSET_START';
export const FETCH_ASSET_SUCCESS = 'FETCH_ASSET_SUCCESS';
export const FETCH_ASSET_FAIL = 'FETCH_ASSET_FAIL';

export const CLEAR_ASSET = 'CLEAR_ASSET';
