export default {
    "EXIF": {
      "Copyright": "(NASA/Aubrey Gemignani)",
      "PhotometricInterpretation": "RGB",
      "ExposureMode": "Manual",
      "FocalPlaneXResolution": 136.8888855,
      "WhiteBalance": "Auto",
      "CustomRendered": "Normal",
      "Contrast": "Normal",
      "Make": "NIKON CORPORATION",
      "FocalLength": "24.0 mm",
      "ExposureProgram": "Manual",
      "FocalLengthIn35mmFormat": "24 mm",
      "PlanarConfiguration": "Chunky",
      "FocalPlaneYResolution": 136.8888855,
      "XResolution": 300,
      "SceneType": "Directly photographed",
      "CreateDate": "2014:08:20 17:50:04",
      "BitsPerSample": "8 8 8",
      "ExifVersion": "0230",
      "Artist": "NASA/Aubrey Gemignani",
      "StripByteCounts": "(Binary data 1363 bytes)",
      "SceneCaptureType": "Standard",
      "CFAPattern": "[Red,Green][Green,Blue]",
      "ResolutionUnit": "inches",
      "SensingMethod": "One-chip color area",
      "StripOffsets": "(Binary data 1719 bytes)",
      "Saturation": "Normal",
      "Software": "Adobe Photoshop Lightroom 4.4 (Macintosh)",
      "Model": "NIKON D4",
      "Sharpness": "Normal",
      "SerialNumber": 2045574,
      "Flash": "No Flash",
      "ShutterSpeedValue": "1/160",
      "LensInfo": "24-70mm f/2.8",
      "SensitivityType": "Recommended Exposure Index",
      "MaxApertureValue": 2.8,
      "RowsPerStrip": 16,
      "ImageHeight": 3248,
      "ExposureCompensation": 0,
      "ISO": 1600,
      "SubjectDistanceRange": "Unknown",
      "ExposureTime": "1/160",
      "ModifyDate": "2014:08:20 20:13:35",
      "LensModel": "24.0-70.0 mm f/2.8",
      "ApertureValue": 2.8,
      "FNumber": 2.8,
      "SubSecTimeOriginal": 10,
      "ImageDescription": "Dr. Shawn Domagal-Goldman, Research Space Scientist, NASA Goddard Space Flight Center, speaks on a panel at the “Ancient Earth, Alien Earths” Event at NASA Headquarters in Washington, DC Wednesday, August 20, 2014. The event was sponsored by NASA, the National Science Foundation (NSF), and the Smithsonian Institution and was moderated by Dr. David H. Grinspoon, Senior Scientist at the Planetary Science Institute. Six scientists discussed how research on early Earth could help guide our search for habitable planets orbiting other stars. Photo Credit: (NASA/Aubrey Gemignani)",
      "SamplesPerPixel": 3,
      "DigitalZoomRatio": 1,
      "SubfileType": "Full-resolution Image",
      "FocalPlaneResolutionUnit": "mm",
      "DateTimeOriginal": "2014:08:20 17:50:04",
      "FileSource": "Digital Camera",
      "MeteringMode": "Multi-segment",
      "LightSource": "Unknown",
      "GainControl": "High gain up",
      "Predictor": "Horizontal differencing",
      "Compression": "LZW",
      "SubSecTimeDigitized": 10,
      "ImageWidth": 4880,
      "YResolution": 300
    },
    "ICC_Profile": {
      "RenderingIntent": "Perceptual",
      "ProfileVersion": "2.1.0",
      "ProfileID": 0,
      "RedMatrixColumn": "0.60974 0.31111 0.01947",
      "ProfileCreator": "ADBE",
      "ProfileClass": "Display Device Profile",
      "ProfileFileSignature": "acsp",
      "ProfileConnectionSpace": "XYZ ",
      "CMMFlags": "Not Embedded, Independent",
      "MediaWhitePoint": "0.95045 1 1.08905",
      "ProfileDateTime": "1999:06:03 00:00:00",
      "DeviceManufacturer": "none",
      "ColorSpaceData": "RGB ",
      "BlueMatrixColumn": "0.14919 0.06322 0.74457",
      "PrimaryPlatform": "Apple Computer Inc.",
      "ProfileDescription": "Adobe RGB (1998)",
      "DeviceAttributes": "Reflective, Glossy, Positive, Color",
      "RedTRC": "(Binary data 14 bytes)",
      "GreenMatrixColumn": "0.20528 0.62567 0.06087",
      "ProfileCopyright": "Copyright 1999 Adobe Systems Incorporated",
      "ConnectionSpaceIlluminant": "0.9642 1 0.82491",
      "ProfileCMMType": "ADBE",
      "BlueTRC": "(Binary data 14 bytes)",
      "MediaBlackPoint": "0 0 0",
      "GreenTRC": "(Binary data 14 bytes)"
    },
    "XMP": {
      "HistoryChanged": "/",
      "CropTop": 0,
      "CropHeight": 3248,
      "Tint": -2,
      "SaturationAdjustmentYellow": 0,
      "ParametricHighlightSplit": 75,
      "Source": "(NASA/Aubrey Gemignani)",
      "MetadataDate": "2014:08:20 20:13:35-04:00",
      "GreenSaturation": 0,
      "DefringeGreenAmount": 0,
      "PaintCorrectionSaturation": 0,
      "Subject": "Ancient Earth Alien Earths Event, Dr. Shawn Domagal-Goldman, Early Earth, Habitable Planets, NASA, NASA HQ, NSF, Panelist, Panelists, Research Space Scientist at NASA Goddard Space Flight Center, Scientists, Smithsonian Institution, Webb Auditorium",
      "CreatorPostalCode": 20545,
      "HistoryParameters": "converted from image/x-nikon-nef to image/tiff, saved to new location",
      "CropRight": 0.992936,
      "Rights": "(NASA/Aubrey Gemignani)",
      "ColorNoiseReductionDetail": 50,
      "PaintCorrectionMoire": 0,
      "CreatorWorkURL": "http://www.nasa.gov",
      "ToneCurvePV2012": "0, 0, 255, 255",
      "PostCropVignetteAmount": 0,
      "PaintCorrectionDefringe": 0,
      "City": "Washington",
      "XMPToolkit": "XMP Core 4.4.0",
      "SaturationAdjustmentGreen": 0,
      "LensID": 147,
      "PaintCorrectionMaskFlow": 1,
      "SharpenDetail": 36,
      "CaptionWriter": "ag",
      "SaturationAdjustmentAqua": 0,
      "AlreadyApplied": true,
      "SharpenRadius": "+1.0",
      "Exposure2012": 0,
      "HueAdjustmentAqua": 0,
      "LuminanceAdjustmentMagenta": 0,
      "ToneCurvePV2012Blue": "0, 0, 255, 255",
      "CreatorWorkTelephone": "202-358-1900",
      "SerialNumber": 2045574,
      "LuminanceAdjustmentGreen": 0,
      "CropBottom": 1,
      "Vibrance": "+20",
      "PaintCorrectionExposure2012": -0.094876,
      "CropLeft": 0.007064,
      "PaintCorrectionShadows2012": 0,
      "ToneCurvePV2012Red": "0, 0, 255, 255",
      "DerivedFromOriginalDocumentID": "DB6CED7734F00E55466C3E4EB84D8651",
      "CreatorAddress": "NASA Headquarters, 300 E Street, SW ",
      "LensProfileSetup": "LensDefaults",
      "ToneCurveName2012": "Linear",
      "ParametricShadowSplit": 25,
      "DateTimeOriginal": "2014:08:20 17:50:04Z",
      "Lens": "24.0-70.0 mm f/2.8",
      "ParametricHighlights": 0,
      "Creator": "NASA/Aubrey Gemignani",
      "ConvertToGrayscale": false,
      "HistorySoftwareAgent": "Adobe Photoshop Lightroom 4.4 (Macintosh)",
      "CropConstrainToWarp": 0,
      "SaturationAdjustmentRed": 0,
      "PaintCorrectionMaskCenterWeight": 0,
      "LuminanceAdjustmentOrange": 0,
      "PaintCorrectionHue": 240,
      "WhiteBalance": "Custom",
      "SplitToningHighlightHue": 0,
      "SharpenEdgeMasking": 80,
      "PaintCorrectionMaskRadius": 0.190823,
      "SaturationAdjustmentBlue": 0,
      "Contrast2012": 0,
      "Title": "Ancient Earth, Alien Earths Event",
      "Marked": false,
      "SplitToningShadowHue": 0,
      "Description": "Dr. Shawn Domagal-Goldman, Research Space Scientist, NASA Goddard Space Flight Center, speaks on a panel at the “Ancient Earth, Alien Earths” Event at NASA Headquarters in Washington, DC Wednesday, August 20, 2014. The event was sponsored by NASA, the National Science Foundation (NSF), and the Smithsonian Institution and was moderated by Dr. David H. Grinspoon, Senior Scientist at the Planetary Science Institute. Six scientists discussed how research on early Earth could help guide our search for habitable planets orbiting other stars. Photo Credit: (NASA/Aubrey Gemignani)",
      "ColorTemperature": 2650,
      "LuminanceSmoothing": 0,
      "PerspectiveVertical": 0,
      "HueAdjustmentMagenta": 0,
      "ShadowTint": 0,
      "RedSaturation": 0,
      "HasCrop": true,
      "HueAdjustmentBlue": 0,
      "Location": "NASA HQ, 300 E St. SW",
      "AutoLateralCA": 0,
      "CropUnit": "pixels",
      "PaintCorrectionAmount": 1,
      "HistoryAction": "derived, saved",
      "SplitToningShadowSaturation": 0,
      "SplitToningBalance": 0,
      "HueAdjustmentOrange": 0,
      "LuminanceAdjustmentAqua": 0,
      "VignetteAmount": 0,
      "CreateDate": "2014:08:20 17:50:04.10",
      "ColorNoiseReduction": 25,
      "CreatorCity": "Washington",
      "PaintCorrectionLuminanceNoise": 0,
      "LensInfo": "24-70mm f/2.8",
      "ImageNumber": 14799,
      "LuminanceAdjustmentBlue": 0,
      "PaintCorrectionTint": 0,
      "PaintCorrectionHighlights2012": 0,
      "DefringePurpleHueHi": 70,
      "LensManualDistortionAmount": 0,
      "ParametricShadows": 0,
      "PaintCorrectionBrightness": 0,
      "Version": 7.4,
      "HueAdjustmentRed": 0,
      "Credit": "(NASA/Aubrey Gemignani)",
      "HistoryWhen": "2014:08:20 20:13:35-04:00",
      "ParametricDarks": 0,
      "DefringeGreenHueHi": 60,
      "HasSettings": true,
      "Highlights2012": 0,
      "BlueSaturation": 0,
      "GreenHue": 0,
      "BlueHue": 0,
      "PerspectiveScale": 100,
      "CreatorTool": "Adobe Photoshop Lightroom 4.4 (Macintosh)",
      "Format": "image/tiff",
      "PaintCorrectionMaskDabs": "d 0.475291 0.534641",
      "Whites2012": "+10",
      "HueAdjustmentYellow": 0,
      "RedHue": 0,
      "ProcessVersion": 6.7,
      "PaintCorrectionMaskValue": 1,
      "SplitToningHighlightSaturation": 0,
      "LensProfileEnable": 0,
      "CropWidth": 4880,
      "TransmissionReference": "201408200002HQ",
      "LuminanceAdjustmentRed": 0,
      "DocumentID": "xmp.did:5454a488-c1f6-4715-9631-b26a02e9cf70",
      "CameraProfile": "Adobe Standard",
      "Blacks2012": -6,
      "LuminanceAdjustmentPurple": 0,
      "ParametricMidtoneSplit": 50,
      "Instructions": "MANDATORY CREDIT: (NASA/Aubrey Gemignani)",
      "SaturationAdjustmentMagenta": 0,
      "HistoryInstanceID": "xmp.iid:5454a488-c1f6-4715-9631-b26a02e9cf70",
      "PaintCorrectionSharpness": 0,
      "Shadows2012": 0,
      "ModifyDate": "2014:08:20 20:13:35Z",
      "PaintCorrectionContrast2012": 0,
      "LuminanceAdjustmentYellow": 0,
      "DerivedFromDocumentID": "DB6CED7734F00E55466C3E4EB84D8651",
      "Headline": "Scientists Speak About Search for Habitable Planets",
      "HueAdjustmentPurple": 0,
      "Saturation": 0,
      "PaintCorrectionMaskWhat": "Mask/Paint",
      "PaintCorrectionActive": true,
      "PerspectiveRotate": 0,
      "DefringePurpleAmount": 0,
      "InstanceID": "xmp.iid:5454a488-c1f6-4715-9631-b26a02e9cf70",
      "DateCreated": "2014:08:20 17:50:04Z",
      "CreatorCountry": "USA",
      "PaintCorrectionTemperature": 0,
      "Country": "USA",
      "Sharpness": 75,
      "ToneCurvePV2012Green": "0, 0, 255, 255",
      "OriginalDocumentID": "DB6CED7734F00E55466C3E4EB84D8651",
      "DefringePurpleHueLo": 30,
      "PaintCorrectionClarity2012": 0,
      "ParametricLights": 0,
      "CreatorRegion": "DC",
      "Rating": 5,
      "SaturationAdjustmentPurple": 0,
      "CropAngle": 0.377054,
      "SaturationAdjustmentOrange": 0,
      "Clarity2012": "+12",
      "ApproximateFocusDistance": 5.01,
      "DefringeGreenHueLo": 40,
      "State": "DC",
      "GrainAmount": 0,
      "PerspectiveHorizontal": 0,
      "PaintCorrectionWhat": "Correction",
      "DateTimeDigitized": "2014:08:20 17:50:04Z",
      "HueAdjustmentGreen": 0
    },
    "IPTC": {
      "DateCreated": "2014:08:20",
      "Keywords": "Ancient Earth Alien Earths Event, Dr. Shawn Domagal-Goldman, Early Earth, Habitable Planets, NASA, NASA HQ, NSF, Panelist, Panelists, Research Space Scientist at NASA Goddard Space Flight Center, Scientists, Smithsonian Institution, Webb Auditorium",
      "Country-PrimaryLocationName": "USA",
      "Credit": "(NASA/Aubrey Gemignani)",
      "ApplicationRecordVersion": 4,
      "Province-State": "DC",
      "Writer-Editor": "ag",
      "CopyrightNotice": "(NASA/Aubrey Gemignani)",
      "DigitalCreationTime": "17:50:04",
      "OriginalTransmissionReference": "201408200002HQ",
      "City": "Washington",
      "Caption-Abstract": "Dr. Shawn Domagal-Goldman, Research Space Scientist, NASA Goddard Space Flight Center, speaks on a panel at the “Ancient Earth, Alien Earths” Event at NASA Headquarters in Washington, DC Wednesday, August 20, 2014. The event was sponsored by NASA, the National Science Foundation (NSF), and the Smithsonian Institution and was moderated by Dr. David H. Grinspoon, Senior Scientist at the Planetary Science Institute. Six scientists discussed how research on early Earth could help guide our search for habitable planets orbiting other stars. Photo Credit: (NASA/Aubrey Gemignani)",
      "ObjectName": "Ancient Earth, Alien Earths Event",
      "Sub-location": "NASA HQ, 300 E St. SW",
      "Headline": "Scientists Speak About Search for Habitable Planets",
      "By-line": "NASA/Aubrey Gemignani",
      "DigitalCreationDate": "2014:08:20",
      "CodedCharacterSet": "UTF8",
      "Source": "(NASA/Aubrey Gemignani)",
      "SpecialInstructions": "MANDATORY CREDIT: (NASA/Aubrey Gemignani)"
    },
    "Other": {
      "SourceFile": "-"
    },
    "AVAIL": {
      "Center": "HQ",
      "DateCreated": "2014:08:20",
      "MediaType": "image",
      "NASAID": "201408200002HQ",
      "Photographer": "NASA/Aubrey Gemignani",
      "Description": "Dr. Shawn Domagal-Goldman, Research Space Scientist, NASA Goddard Space Flight Center, speaks on a panel at the “Ancient Earth, Alien Earths” Event at NASA Headquarters in Washington, DC Wednesday, August 20, 2014. The event was sponsored by NASA, the National Science Foundation (NSF), and the Smithsonian Institution and was moderated by Dr. David H. Grinspoon, Senior Scientist at the Planetary Science Institute. Six scientists discussed how research on early Earth could help guide our search for habitable planets orbiting other stars. Photo Credit: (NASA/Aubrey Gemignani)",
      "Keywords": "Ancient Earth Alien Earths Event, Dr. Shawn Domagal-Goldman, Early Earth, Habitable Planets, NASA, NASA HQ, NSF, Panelist, Panelists, Research Space Scientist at NASA Goddard Space Flight Center, Scientists, Smithsonian Institution, Webb Auditorium",
      "Location": "NASA HQ, 300 E St. SW",
      "Owner": "rlobrie1",
      "Title": "Ancient Earth, Alien Earths Event"
    },
    "File": {
      "FileName": "201408200002HQ.tif",
      "FileSize": "21 MB",
      "FileAccessDate": "2015:09:03 16:55:11+00:00",
      "FileInodeChangeDate": "2015:09:03 16:55:11+00:00",
      "CurrentIPTCDigest": "90139b9b339d4bc90f2db2f172abb0ce",
      "FileType": "TIFF",
      "MIMEType": "image/tiff",
      "FilePermissions": "rw-------",
      "FileModifyDate": "2015:09:03 16:55:11+00:00",
      "ExifByteOrder": "Little-endian (Intel, II)"
    },
    "Composite": {
      "FocalLength35efl": "24.0 mm (35 mm equivalent: 24.0 mm)",
      "LightValue": 6.3,
      "SubSecCreateDate": "2014:08:20 17:50:04.10",
      "ImageSize": "4880x3248",
      "SubSecDateTimeOriginal": "2014:08:20 17:50:04.10",
      "FOV": "73.7 deg",
      "HyperfocalDistance": "6.85 m",
      "DigitalCreationDateTime": "2014:08:20 17:50:04",
      "Aperture": 2.8,
      "ShutterSpeed": "1/160",
      "LensID": "AF-S Zoom-Nikkor 24-70mm f/2.8G ED",
      "CircleOfConfusion": "0.030 mm",
      "ScaleFactor35efl": 1
    },
    "Photoshop": {
      "PhotoshopThumbnail": "(Binary data 12571 bytes)",
      "IPTCDigest": "dcf0b960fcfe307b87f177b697f7da0a",
      "CopyrightFlag": false
    },
    "ExifTool": {
      "ExifToolVersion": 9.46
    }
  }